## Packages&Modules
- Libraries in C
- packages in java
- modules in python
- set of statements together called as a function
- set of functions called as a module
- set of modules called as a package

## modules
- module is python file which contains python coding
- Type
  - pre-defined modules
  - user-defined modules
- syntax
  - import module_name

### Package
- collection of modules

#### predefined modules

In [60]:
help('modules')


Please wait a moment while I gather a list of all available modules...



C:\Users\HP\anaconda3\lib\site-packages\IPython\kernel\__init__.py:12: ShimWarning: The `IPython.kernel` package has been deprecated since IPython 4.0.You should import from ipykernel or jupyter_client instead.
  warn("The `IPython.kernel` package has been deprecated since IPython 4.0."
Matplotlib is building the font cache; this may take a moment.
C:\Users\HP\anaconda3\lib\pkgutil.py:92: MatplotlibDeprecationWarning: 
The matplotlib.compat module was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
  __import__(info.name)
C:\Users\HP\anaconda3\lib\site-packages\nltk\twitter\__init__.py:21: UserWarning: The twython library has not been installed. Some functionality from the twitter package will not be available.
  warnings.warn(
C:\Users\HP\anaconda3\lib\site-packages\skimage\viewer\utils\__init__.py:1: UserWarning: Recommended matplotlib backend is `Agg` for full skimage.viewer functionality.
  from .core import *


Update LANGUAGE_CODES (inside config/base.py) if a new translation has been added to Spyder


C:\Users\HP\anaconda3\lib\site-packages\qtawesome\iconic_font.py:313: UserWarning: You need to have a running QApplication to use QtAwesome!
  warnings.warn("You need to have a running "
C:\Users\HP\anaconda3\lib\pkgutil.py:107: VisibleDeprecationWarning: zmq.eventloop.minitornado is deprecated in pyzmq 14.0 and will be removed.
    Install tornado itself to use zmq with the tornado IOLoop.
    
  yield from walk_packages(path, info.name+'.', onerror)


Cython              brain_re            mailbox             sndhdr
IPython             brain_responses     mailcap             sniffio
OpenSSL             brain_scipy_signal  markupsafe          snowballstemmer
PIL                 brain_six           marshal             socket
PyQt5               brain_sqlalchemy    math                socketserver
__future__          brain_ssl           matplotlib          socks
_abc                brain_subprocess    mccabe              sockshandler
_ast                brain_threading     menuinst            sortedcollections
_asyncio            brain_type          mimetypes           sortedcontainers
_bisect             brain_typing        mistune             soupsieve
_black_version      brain_uuid          mkl                 sphinx
_blake2             brotli              mkl_fft             sphinxcontrib
_bootlocale         bs4                 mkl_random          spyder
_bz2                builtins            mmap                spyder_kernels
_c

In [1]:
import math

In [2]:
print(dir(math))

['__doc__', '__loader__', '__name__', '__package__', '__spec__', 'acos', 'acosh', 'asin', 'asinh', 'atan', 'atan2', 'atanh', 'ceil', 'comb', 'copysign', 'cos', 'cosh', 'degrees', 'dist', 'e', 'erf', 'erfc', 'exp', 'expm1', 'fabs', 'factorial', 'floor', 'fmod', 'frexp', 'fsum', 'gamma', 'gcd', 'hypot', 'inf', 'isclose', 'isfinite', 'isinf', 'isnan', 'isqrt', 'ldexp', 'lgamma', 'log', 'log10', 'log1p', 'log2', 'modf', 'nan', 'perm', 'pi', 'pow', 'prod', 'radians', 'remainder', 'sin', 'sinh', 'sqrt', 'tan', 'tanh', 'tau', 'trunc']


In [5]:
help(math.sqrt)

Help on built-in function sqrt in module math:

sqrt(x, /)
    Return the square root of x.



In [6]:
print(math.sqrt(81))

9.0


In [7]:
print(int(math.sqrt(81)))

9


In [8]:
print(math.pow(9,4))#9**4

6561.0


In [12]:
help(math.pi)

Help on float object:

class float(object)
 |  float(x=0, /)
 |  
 |  Convert a string or number to a floating point number, if possible.
 |  
 |  Methods defined here:
 |  
 |  __abs__(self, /)
 |      abs(self)
 |  
 |  __add__(self, value, /)
 |      Return self+value.
 |  
 |  __bool__(self, /)
 |      self != 0
 |  
 |  __divmod__(self, value, /)
 |      Return divmod(self, value).
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __float__(self, /)
 |      float(self)
 |  
 |  __floordiv__(self, value, /)
 |      Return self//value.
 |  
 |  __format__(self, format_spec, /)
 |      Formats the float according to format_spec.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __getnewargs__(self, /)
 |  
 |  __gt__(self, value, /)
 |      Return self>value.
 |  
 |  __hash__(self, /)
 |      Return hash(self).
 |  
 |  __int__(self, /)
 |      int(self)
 |  
 |  __le__

In [14]:
math.pi

3.141592653589793

In [15]:
help(math.e)

Help on float object:

class float(object)
 |  float(x=0, /)
 |  
 |  Convert a string or number to a floating point number, if possible.
 |  
 |  Methods defined here:
 |  
 |  __abs__(self, /)
 |      abs(self)
 |  
 |  __add__(self, value, /)
 |      Return self+value.
 |  
 |  __bool__(self, /)
 |      self != 0
 |  
 |  __divmod__(self, value, /)
 |      Return divmod(self, value).
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __float__(self, /)
 |      float(self)
 |  
 |  __floordiv__(self, value, /)
 |      Return self//value.
 |  
 |  __format__(self, format_spec, /)
 |      Formats the float according to format_spec.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __getnewargs__(self, /)
 |  
 |  __gt__(self, value, /)
 |      Return self>value.
 |  
 |  __hash__(self, /)
 |      Return hash(self).
 |  
 |  __int__(self, /)
 |      int(self)
 |  
 |  __le__

In [16]:
import random

In [17]:
dir(random)

['BPF',
 'LOG4',
 'NV_MAGICCONST',
 'RECIP_BPF',
 'Random',
 'SG_MAGICCONST',
 'SystemRandom',
 'TWOPI',
 '_Sequence',
 '_Set',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 '_accumulate',
 '_acos',
 '_bisect',
 '_ceil',
 '_cos',
 '_e',
 '_exp',
 '_inst',
 '_log',
 '_os',
 '_pi',
 '_random',
 '_repeat',
 '_sha512',
 '_sin',
 '_sqrt',
 '_test',
 '_test_generator',
 '_urandom',
 '_warn',
 'betavariate',
 'choice',
 'choices',
 'expovariate',
 'gammavariate',
 'gauss',
 'getrandbits',
 'getstate',
 'lognormvariate',
 'normalvariate',
 'paretovariate',
 'randint',
 'random',
 'randrange',
 'sample',
 'seed',
 'setstate',
 'shuffle',
 'triangular',
 'uniform',
 'vonmisesvariate',
 'weibullvariate']

In [21]:
random.randint(10,50)

11

In [26]:
import calendar

In [27]:
print(calendar.calendar(2022))

                                  2022

      January                   February                   March
Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su
                1  2          1  2  3  4  5  6          1  2  3  4  5  6
 3  4  5  6  7  8  9       7  8  9 10 11 12 13       7  8  9 10 11 12 13
10 11 12 13 14 15 16      14 15 16 17 18 19 20      14 15 16 17 18 19 20
17 18 19 20 21 22 23      21 22 23 24 25 26 27      21 22 23 24 25 26 27
24 25 26 27 28 29 30      28                        28 29 30 31
31

       April                      May                       June
Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su
             1  2  3                         1             1  2  3  4  5
 4  5  6  7  8  9 10       2  3  4  5  6  7  8       6  7  8  9 10 11 12
11 12 13 14 15 16 17       9 10 11 12 13 14 15      13 14 15 16 17 18 19
18 19 20 21 22 23 24      16 17 18 19 20 21 22      20 21 22 23 24 25 26
25 26 27 28 29 30         23 24 

In [36]:
print(calendar.month(2022,10))


    October 2022
Mo Tu We Th Fr Sa Su
                1  2
 3  4  5  6  7  8  9
10 11 12 13 14 15 16
17 18 19 20 21 22 23
24 25 26 27 28 29 30
31



### User-defined modules

In [2]:
import mymodule

In [2]:
mymodule.addition(4,6)

10


In [3]:
mymodule.factorial(4)

11


In [2]:
mymodule.evenOdd(5)

odd number


In [3]:
mymodule.evenOdd(8)

Even number


In [5]:
mymodule.primeNot(7)

7 is prime


## Python libraries
- Numpy
- pandas
- matplotlib
- seaborn
- scikit learn
- Tensorflow
- keras

### Numpy(numerical python)
- mainly design mathematical comutational purpose

#### installation and importing numpy
- pip install numpy
- conda install numpy

In [36]:
import numpy as np

In [37]:
np.__version__

'1.20.1'

In [38]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'Bytes0', 'CLIP', 'ComplexWarning', 'DataSource', 'Datetime64', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Str0', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'Uint64', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__getattr__', '__git_revision__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__sp

**Create numpy arrays in different ways**

In [39]:
n1=np.array([1,10,100,1000])
n1

array([   1,   10,  100, 1000])

In [40]:
print(type(n1))

<class 'numpy.ndarray'>


In [41]:
print(n1.ndim)

1


In [42]:
print(n1.itemsize)

4


In [43]:
print(n1.dtype)

int32


In [44]:
n1=np.array([1.9,10,100,1000])
n1

array([   1.9,   10. ,  100. , 1000. ])

In [45]:
n1.dtype

dtype('float64')

In [46]:
n1=np.array([1.9,10,100,1000,'AITS'])
print(n1)
print(n1.dtype)

['1.9' '10' '100' '1000' 'AITS']
<U32


## How to create 2-dimensional array

In [47]:
#syntax for 2-dimensional array
### np.array([[row1],[row2]----[rown]])

In [48]:
n2=np.array([[1,2,3,4],[5,6,7,8]])
n2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [49]:
print(n2.ndim)

2


In [50]:
print(n2.shape)

(2, 4)


## 3-Dimesional or multi-dimensional array

In [57]:
##syntax for 3-dimensional array
#np.array([[[],[]]])

In [52]:
n3=np.array([[[1,2,3],[10,20,30]]])
n3

array([[[ 1,  2,  3],
        [10, 20, 30]]])

In [53]:
n3.ndim

3

In [54]:
print(n3.shape)

(1, 2, 3)


In [55]:
n3.dtype

dtype('int32')

In [56]:
n3.itemsize

4

In [ ]:
#Task1 reverse of the number
#Task2 palindrome

In [67]:
##input  123
##output 321
n=int(input("enter a number"))
rev=0    
while(n!=0):   ##n=123       #n=12              #n=1
    rem=n%10  ##rem=3        #r=12%10=2         #r=1%10=1
    rev=rev*10+rem##rev=0+3  #rev=3*10+2=32     #rev=32*10+1=321
    n=n//10    ##n=12        #n=12//10=1        #n=1//10=0
print(rev)

enter a number123
321


In [65]:
1%10

1

In [66]:
1//10

0