**why numpy? when we have list**

In [1]:
list1=[1,1,1]
print(list1+9)

TypeError: can only concatenate list (not "int") to list

In [3]:
import numpy as np

In [4]:
numpy1=np.array([1,1,1])
print(numpy1+9)

[10 10 10]


#### Advantages of numpy
- numpy arrays are more compact than list
- it will take very less time to execute a program 
-  it will take less storage space

## Numpy methods
- np.arange()
- np.linspace()
- np.ones()
- np.zeros()
- reshape()
- statistical methods
- random methods 

### How can we use for loop Vs np.arange()

In [5]:
for i in range(10,20):
    print(i)

10
11
12
13
14
15
16
17
18
19


In [6]:
range(10,20)

range(10, 20)

In [8]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [9]:
np.arange(0,101,5)
## 0--->start value
## 101-->stop value
## 5---->stepsize

array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100])

**np.linspace()**

In [10]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [11]:
1.57894737- 1.05263158

0.5263157900000002

In [12]:
6.84210526-6.31578947

0.52631579

In [16]:
np.linspace(10,30,50)

array([10.        , 10.40816327, 10.81632653, 11.2244898 , 11.63265306,
       12.04081633, 12.44897959, 12.85714286, 13.26530612, 13.67346939,
       14.08163265, 14.48979592, 14.89795918, 15.30612245, 15.71428571,
       16.12244898, 16.53061224, 16.93877551, 17.34693878, 17.75510204,
       18.16326531, 18.57142857, 18.97959184, 19.3877551 , 19.79591837,
       20.20408163, 20.6122449 , 21.02040816, 21.42857143, 21.83673469,
       22.24489796, 22.65306122, 23.06122449, 23.46938776, 23.87755102,
       24.28571429, 24.69387755, 25.10204082, 25.51020408, 25.91836735,
       26.32653061, 26.73469388, 27.14285714, 27.55102041, 27.95918367,
       28.36734694, 28.7755102 , 29.18367347, 29.59183673, 30.        ])

In [13]:
help(np.linspace)

Help on function linspace in module numpy:

linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
    Return evenly spaced numbers over a specified interval.
    
    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].
    
    The endpoint of the interval can optionally be excluded.
    
    .. versionchanged:: 1.16.0
        Non-scalar `start` and `stop` are now supported.
    
    .. versionchanged:: 1.20.0
        Values are rounded towards ``-inf`` instead of ``0`` when an
        integer ``dtype`` is specified. The old behavior can
        still be obtained with ``np.linspace(start, stop, num).astype(int)``
    
    Parameters
    ----------
    start : array_like
        The starting value of the sequence.
    stop : array_like
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, so that 

In [15]:
np.linspace(0,10,20,retstep=True)

(array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
         2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
         5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
         7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ]),
 0.5263157894736842)

**np.ones()**

In [17]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [18]:
np.ones([2,3])

array([[1., 1., 1.],
       [1., 1., 1.]])

In [19]:
np.ones([3,2,4])
##3-->n0.of matrices
##2-->rows
##4-->columns

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [20]:
np.ones(5,dtype=int)

array([1, 1, 1, 1, 1])

**np.zeros()**

In [21]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [22]:
np.zeros(5,dtype=int)

array([0, 0, 0, 0, 0])

In [23]:
np.zeros([3,2,4])

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

**reshape()**
- Giving new shape to an array 

In [25]:
a=np.array([[1,10,20,2],[11,7,102,18]])
a

array([[  1,  10,  20,   2],
       [ 11,   7, 102,  18]])

In [26]:
a.shape

(2, 4)

- The product of rows and columns in the new array should be equal to total no.of elements 

In [ ]:
#2*4=8
#4*2=8
#8*1=8
#1*8=8

In [27]:
a.reshape(4,2)

array([[  1,  10],
       [ 20,   2],
       [ 11,   7],
       [102,  18]])

In [29]:
a.reshape(1,8)

array([[  1,  10,  20,   2,  11,   7, 102,  18]])

In [30]:
a.reshape(8,1)

array([[  1],
       [ 10],
       [ 20],
       [  2],
       [ 11],
       [  7],
       [102],
       [ 18]])

In [31]:
a.reshape(8,2)

ValueError: cannot reshape array of size 8 into shape (8,2)

**Statistical methods**

In [32]:
a1=np.arange(10,30)
a1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29])

In [33]:
len(a1)

20

In [ ]:
#4*5=20
#5*4=20
#2*10=20
#10*2=20
#1*20=20
#20*1=20

In [34]:
a2=a1.reshape(4,5)
print(a2)

[[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]


In [35]:
print(np.max(a2))

29


In [36]:
print(np.min(a2))

10


In [37]:
print(np.argmax(a2))#index position of  maximum value of array a2

19


In [38]:
print(np.argmin(a2))#index position of minimum value of array a2

0


In [39]:
print(np.sum(a2))#sum of total elements in array

390


In [40]:
print(np.mean(a2))#mean value of array

19.5


In [41]:
print(np.median(a2))#median value of array

19.5


In [42]:
print(np.log(10))

2.302585092994046


In [43]:
print(np.log2(10))

3.321928094887362


In [44]:
print(np.log10(10))

1.0


In [45]:
print(np.sin(3.14/6))#pi value=3.14

0.4997701026431024


In [46]:
print(np.cos(3.14/3))

0.5004596890082058


In [47]:
print(np.tan(3.14/4))

0.9992039901050427


In [48]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'Bytes0', 'CLIP', 'ComplexWarning', 'DataSource', 'Datetime64', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Str0', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'Uint64', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__getattr__', '__git_revision__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__sp

**random methods**

In [49]:
import numpy as np

In [58]:
np.random.randint(5)

4

In [65]:
np.random.randint(10,25)

17

In [68]:
np.random.randint(10,25,2)
#syntax np.random.randint(start,stop,no.of random values)
# 10-->start value
# 25-->stop value
# 2--->no.of random values that you want to generate

array([23, 15])

In [71]:
np.random.rand()#by default range is 0 t0 1

0.4118858708347426

In [74]:
np.random.rand(10)#every time it generates ramdom value in between 0 t0 1
#10--->no.of random values

array([0.47569326, 0.68270787, 0.22858947, 0.03415117, 0.56347875,
       0.78334237, 0.93992681, 0.22165943, 0.71873108, 0.44401834])

In [75]:
np.random.rand(2,5)

array([[0.76200044, 0.77292341, 0.22690625, 0.3905706 , 0.26670559],
       [0.73649424, 0.23133547, 0.3707648 , 0.61659952, 0.32233092]])

In [78]:
np.random.rand(5,2)

array([[0.42456734, 0.69888697],
       [0.09983595, 0.85775708],
       [0.9755198 , 0.00605324],
       [0.70746882, 0.52324385],
       [0.13157517, 0.49252735]])

In [81]:
np.random.randint(10,20,[5,2])

array([[12, 14],
       [12, 18],
       [10, 14],
       [12, 13],
       [16, 17]])